import logging
from importlib.metadata import PackageNotFoundError, version
from typing import Any, Dict

from gigachat._compat import warn_deprecated_symbol
from gigachat.clients import GigaChat, GigaChatAsyncClient, GigaChatSyncClient
from gigachat.context import (
    agent_id_cvar,
    authorization_cvar,
    chat_url_cvar,
    chat_v2_url_cvar,
    client_id_cvar,
    custom_headers_cvar,
    operation_id_cvar,
    request_id_cvar,
    service_id_cvar,
    session_id_cvar,
    trace_id_cvar,
)
from gigachat.exceptions import (
    AuthenticationError,
    BadRequestError,
    ContentFilterFinishReasonError,
    ContentParseError,
    ContentValidationError,
    ForbiddenError,
    GigaChatException,
    LengthFinishReasonError,
    NotFoundError,
    RateLimitError,
    RequestEntityTooLargeError,
    ResponseError,
    ServerError,
    UnprocessableEntityError,
)
from gigachat.schemas import (
    AccessToken,
    AICheckResult,
    Assistant,
    AssistantAttachment,
    AssistantDelete,
    AssistantFileDelete,
    AssistantList,
    Balance,
    BalanceValue,
    BatchList,
    ChatFunctionCall,
    CompletionChoice,
    CompletionChoiceChunk,
    CreateAssistant,
    DeletedFile,
    Embedding,
    Embeddings,
    EmbeddingsUsage,
    File,
    Function,
    FunctionCall,
    FunctionParameters,
    FunctionParametersProperty,
    FunctionRanker,
    FunctionValidationIssue,
    FunctionValidationResult,
    Image,
    JsonSchemaResponseFormat,
    LegacyChatRequest,
    LegacyChatResponse,
    LegacyChatStreamChunk,
    LegacyMessage,
    LegacyMessageRole,
    LogProbToken,
    MessageLogProb,
    ModelInfo,
    ModelList,
    OpenApiFunctions,
    ResponseFormat,
    Storage,
    StructuredChatRequest,
    StructuredChatResponse,
    StructuredChatStreamChunk,
    StructuredContentPart,
    StructuredMessage,
    StructuredTool,
    Thread,
    ThreadCompletion,
    ThreadCompletionChunk,
    ThreadList,
    ThreadMessage,
    ThreadMessageAttachment,
    ThreadMessageResponse,
    ThreadMessages,
    ThreadMessagesResponse,
    ThreadRunOptions,
    ThreadRunResponse,
    ThreadRunResult,
    ThreadStatus,
    Token,
    TokensCount,
    UploadedFile,
    UploadedFiles,
    Usage,
)
from gigachat.schemas import (
    Batch as _Batch,
)
from gigachat.schemas import (
    Batches as _Batches,
)

try:
    __version__ = version("gigachat")
except PackageNotFoundError:
    __version__ = "0.2.2a1"

_DEPRECATED_EXPORTS: Dict[str, Any] = {
    "Batch": _Batch,
    "Batches": _Batches,
    "Chat": LegacyChatRequest,
    "ChatCompletion": LegacyChatResponse,
    "ChatCompletionChunk": LegacyChatStreamChunk,
    "ChatCompletionV2": StructuredChatResponse,
    "ChatCompletionV2Chunk": StructuredChatStreamChunk,
    "ChatV2": StructuredChatRequest,
    "ChatV2ContentPart": StructuredContentPart,
    "ChatV2Message": StructuredMessage,
    "Choices": CompletionChoice,
    "Messages": LegacyMessage,
    "MessagesRole": LegacyMessageRole,
    "Model": ModelInfo,
    "Models": ModelList,
}

__all__ = [
    "__version__",
    "AccessToken",
    "AICheckResult",
    "agent_id_cvar",
    "Assistant",
    "AssistantAttachment",
    "AssistantDelete",
    "AssistantFileDelete",
    "AssistantList",
    "AuthenticationError",
    "authorization_cvar",
    "BadRequestError",
    "Balance",
    "BalanceValue",
    "Batch",
    "BatchList",
    "Batches",
    "chat_url_cvar",
    "chat_v2_url_cvar",
    "Chat",
    "ChatCompletion",
    "ChatCompletionChunk",
    "ChatCompletionV2",
    "ChatCompletionV2Chunk",
    "ChatFunctionCall",
    "ChatV2",
    "ChatV2ContentPart",
    "ChatV2Message",
    "Choices",
    "client_id_cvar",
    "CompletionChoice",
    "CompletionChoiceChunk",
    "ContentFilterFinishReasonError",
    "ContentParseError",
    "ContentValidationError",
    "CreateAssistant",
    "custom_headers_cvar",
    "DeletedFile",
    "Embedding",
    "Embeddings",
    "EmbeddingsUsage",
    "File",
    "ForbiddenError",
    "Function",
    "FunctionCall",
    "FunctionParameters",
    "FunctionParametersProperty",
    "FunctionRanker",
    "FunctionValidationIssue",
    "FunctionValidationResult",
    "GigaChat",
    "GigaChatAsyncClient",
    "GigaChatException",
    "GigaChatSyncClient",
    "Image",
    "JsonSchemaResponseFormat",
    "LegacyChatRequest",
    "LegacyChatResponse",
    "LegacyChatStreamChunk",
    "LegacyMessage",
    "LegacyMessageRole",
    "LengthFinishReasonError",
    "LogProbToken",
    "MessageLogProb",
    "Messages",
    "MessagesRole",
    "Model",
    "ModelInfo",
    "ModelList",
    "Models",
    "NotFoundError",
    "OpenApiFunctions",
    "operation_id_cvar",
    "RateLimitError",
    "request_id_cvar",
    "RequestEntityTooLargeError",
    "ResponseError",
    "ResponseFormat",
    "ServerError",
    "service_id_cvar",
    "session_id_cvar",
    "Storage",
    "StructuredChatRequest",
    "StructuredChatResponse",
    "StructuredChatStreamChunk",
    "StructuredContentPart",
    "StructuredMessage",
    "StructuredTool",
    "Thread",
    "ThreadCompletion",
    "ThreadCompletionChunk",
    "ThreadList",
    "ThreadMessage",
    "ThreadMessageAttachment",
    "ThreadMessageResponse",
    "ThreadMessages",
    "ThreadMessagesResponse",
    "ThreadRunOptions",
    "ThreadRunResponse",
    "ThreadRunResult",
    "ThreadStatus",
    "Token",
    "TokensCount",
    "trace_id_cvar",
    "UnprocessableEntityError",
    "UploadedFile",
    "UploadedFiles",
    "Usage",
]


def __getattr__(name: str) -> Any:
    try:
        value = _DEPRECATED_EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    warn_deprecated_symbol(f"gigachat.{name}", _canonical_name(name), stacklevel=2)
    return value


def _canonical_name(name: str) -> str:
    mapping = {
        "Batch": "gigachat.BatchList item / gigachat.schemas.Batch",
        "Batches": "gigachat.BatchList",
        "Chat": "gigachat.LegacyChatRequest",
        "ChatCompletion": "gigachat.LegacyChatResponse",
        "ChatCompletionChunk": "gigachat.LegacyChatStreamChunk",
        "ChatCompletionV2": "gigachat.StructuredChatResponse",
        "ChatCompletionV2Chunk": "gigachat.StructuredChatStreamChunk",
        "ChatV2": "gigachat.StructuredChatRequest",
        "ChatV2ContentPart": "gigachat.StructuredContentPart",
        "ChatV2Message": "gigachat.StructuredMessage",
        "Choices": "gigachat.CompletionChoice",
        "Messages": "gigachat.LegacyMessage",
        "MessagesRole": "gigachat.LegacyMessageRole",
        "Model": "gigachat.ModelInfo",
        "Models": "gigachat.ModelList",
    }
    return mapping[name]


logging.getLogger(__name__).addHandler(logging.NullHandler())
